name:                bitcoin
version:             0.1.1.0
homepage:            https://github.com/johnjago/bitcoin#readme
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - lens-aeson
  - bytestring
  - text
  - http-conduit

executables:
  bitcoin:
    source-dirs:      src
    main:             Main.hs
